// ===== LANGUAGE SYSTEM =====
const LANG = {
    'en': {
        'home': 'Home', 'xrd': 'XRD', 'ftir': 'FTIR', 'bet': 'BET', 'projects': 'Projects', 'contact': 'Contact',
        'hero_title': 'Environmental Engineering',
        'hero_subtitle': 'Research & Analysis',
        'hero_desc': 'Advanced characterization tools for biochar, adsorbents, and water treatment materials. Upload XRD, FTIR, BET data for instant visualization and analysis.',
        'start_analysis': 'Start Analysis',
        'view_projects': 'View Projects',
        'analysis_tools': 'Analysis Tools',
        'choose_tool': 'Choose Your Characterization Method',
        'click_tool': 'Click any tool to open its dedicated analysis page.',
        'xrd_desc': 'Peak detection, d-spacing, crystallinity index, crystallite size',
        'ftir_desc': 'Functional group ID, band assignment, baseline correction',
        'bet_desc': 'Surface area, pore volume, isotherm classification, BJH',
        'open_xrd': 'Open XRD Tool',
        'open_ftir': 'Open FTIR Tool',
        'open_bet': 'Open BET Tool',
        'samples': 'Samples Analyzed',
        'research': 'Research Projects',
        'publications': 'Publications',
        'q1': 'Q1 Journals',
        'current_projects': 'Current Research Projects',
        'project_desc': 'Environmental engineering research focused on biochar-based materials for water treatment.',
        'q1_target': 'Q1 Target',
        'in_progress': 'In Progress',
        'planning': 'Planning',
        'get_in_touch': 'Get In Touch',
        'collaboration': 'For collaboration, data sharing, or research inquiries.',
        'institution': 'Institution',
        'location': 'Location',
        'research_focus': 'Research Focus',
        'biochar_water': 'Biochar, Water Treatment, Heavy Metal Removal',
        'send_message': 'Send Message',
        'built_for': 'Built for research. Open source.',
        'drag_drop': 'Drag & drop files',
        'browse': 'Browse',
        'sample_data': 'Sample Data:',
        'upload_data': 'Upload data or select a sample to begin',
        'peak_detection': 'Peak Detection',
        'min_peak': 'Min Peak Height (%)',
        'smoothing': 'Smoothing Factor',
        'peak_width': 'Peak Width (points)',
        'detect_peaks': 'Detect Peaks',
        'peak_params': 'Peak Parameters',
        'range': 'Range',
        'max_intensity': 'Max Intensity',
        'peak_count': 'Peak Count',
        'fwhm': 'FWHM (avg)',
        'crystallinity': 'Crystallinity Index',
        'avg_area': 'Avg Peak Area',
        'export_peak': 'Export Peak Data',
        'crystal_info': 'Crystal Info',
        'wavelength': 'Wavelength (Å)',
        'instrument': 'Instrument',
        'calc_d': 'Calculate d-spacing',
        'detailed_peak': 'Detailed Peak Analysis',
        'functional_group': 'Functional Group Identification',
        'spectrum_settings': 'Spectrum Settings',
        'baseline': 'Baseline Correction',
        'none': 'None',
        'linear': 'Linear',
        'polynomial': 'Polynomial (2nd order)',
        'rubberband': 'Rubber Band',
        'savgol': 'Smoothing (Savitzky-Golay)',
        'normalization': 'Normalization',
        'max_norm': 'Max Normalization',
        'area_norm': 'Area Normalization',
        'minmax': 'Min-Max',
        'spectrum_stats': 'Spectrum Statistics',
        'resolution': 'Resolution',
        'min_t': 'Min Transmittance',
        'max_t': 'Max Transmittance',
        'detected_bands': 'Detected Bands',
        'snr': 'Signal/Noise Ratio',
        'bet_calculator': 'BET Calculator',
        'cross_section': 'Cross-sectional area (Å²)',
        'mol_weight': 'Molecular weight (g/mol)',
        'stp': 'STP volume (cm³/mol)',
        'bet_range': 'BET Range (P/P₀)',
        'results_summary': 'Results Summary',
        'surface_area': 'BET Surface Area',
        'pore_volume': 'Total Pore Volume',
        'micro_volume': 'Micropore Volume',
        'meso_volume': 'Mesopore Volume',
        'avg_pore': 'Average Pore Size',
        'correlation': 'Correlation R²',
        'monolayer': 'Monolayer Volume',
        'bet_c': 'BET Constant C',
        'isotherm_class': 'Isotherm Classification',
        'microporous': 'Microporous',
        'non_porous': 'Non-porous',
        'weak': 'Weak interaction',
        'mesoporous': 'Mesoporous',
        'capillary': 'Weak + capillary',
        'layered': 'Layered',
        'detailed_data': 'Detailed Isotherm Data',
        'metadata': 'Analysis Metadata',
        'export': 'Export',
        'png_300': 'PNG (300 DPI)',
        'png_600': 'PNG (600 DPI)',
        'png_1000': 'PNG (1000 DPI)',
        'data_csv': 'Data (CSV)',
        'data_txt': 'Data (TXT)',
        'full_report': 'Full Report',
        'no_peaks': 'No peaks detected yet',
        'no_dspacing': 'Detect peaks to calculate d-spacing',
        'upload_first': 'Upload data first',
        'detect_first': 'Detect peaks first',
        'xrd_analysis': 'X-Ray Diffraction Data Visualization',
        'xrd_desc_long': 'Upload your XRD data to generate publication-ready graphs with peak detection, d-spacing calculation, and comprehensive metadata.',
        'ftir_analysis': 'Fourier Transform Infrared Spectroscopy',
        'ftir_desc_long': 'Upload FTIR spectra for functional group identification, peak analysis, and band assignment.',
        'bet_analysis': 'Surface Area & Porosity Analysis',
        'bet_desc_long': 'Upload N₂ adsorption/desorption isotherm data for comprehensive surface area and pore characterization.',
        'wavenumber': 'Wavenumber (cm⁻¹)',
        'vibration_type': 'Vibration Type',
        'expected_range': 'Expected Range',
        'observed': 'Observed Intensity',
        'band_shape': 'Band Shape',
        'status': 'Status',
        'detected': 'Detected',
        'not_detected': 'Not Detected',
        'point_num': 'Point #',
        'p_p0': 'P/P₀',
        'adsorption': 'Adsorption (cm³/g)',
        'desorption': 'Desorption (cm³/g)',
        'hysteresis': 'Hysteresis',
        'bet_y': '1/[V(P₀/P-1)]',
        'in_range': 'In BET Range',
        'tea_biochar': 'Tea Branch Biochar',
        'koh_activated': 'KOH-Activated',
        'fe_modified': 'Fe-Modified Biochar',
        'zno': 'ZnO Nanoparticles',
        'tio2': 'TiO₂ Anatase',
        'raw_biochar': 'Raw Biochar',
        'chitosan': 'Chitosan-Biochar',
        'meso_silica': 'Mesoporous Silica',
        'macro_carbon': 'Macroporous Carbon',
        'cd_removal': 'Tea Branch Biochar for Cd²⁺ Removal',
        'cd_desc': 'Preparation and characterization of tea branch biochar for cadmium removal from aqueous solutions.',
        'pnp': 'PNP Degradation Study',
        'pnp_desc': 'p-Nitrophenol degradation using modified biochar catalysts. Kinetic modeling.',
        'as_removal': 'Fe-Modified Biochar for As Removal',
        'as_desc': 'Iron-impregnated biochar for arsenic removal from groundwater.',
        'env_eng': 'Environmental Engineering Department',
        'china': 'China',
        'name': 'Name',
        'email': 'Email',
        'subject': 'Subject',
        'message': 'Message',
        'research_collab': 'Research Collaboration',
        'data_help': 'Data Analysis Help',
        'general': 'General Inquiry',
        'platform': 'Environmental Engineering Research & Data Analysis Platform',
        'xrd_pattern': 'XRD Pattern',
        'ftir_spectrum': 'FTIR Spectrum',
        'bet_isotherm': 'N₂ Adsorption/Desorption Isotherm',
        'intensity_pct': 'Intensity (%)',
        'transmittance_pct': 'Transmittance (%)',
        'absorbance': 'Absorbance (a.u.)',
        'n2_adsorbed': 'N₂ Adsorbed (cm³/g STP)',
        'relative_pressure': 'Relative Pressure (P/P₀)',
        'intensity_cps': 'Intensity (cps)',
        'relative_pct': 'Relative (%)',
        'd_spacing': 'd-spacing (Å)',
        'peak_area': 'Peak Area',
        'cryst_size': 'Crystallite Size (nm)',
        'total_points': 'Total Points',
        'step_size': 'Step Size',
        'max_int': 'Max Intensity',
        'mean_int': 'Mean Intensity',
        'std_dev': 'Std Deviation',
        'loaded': 'Loaded',
        'filename': 'File Name',
        'has_desorption': 'Has Desorption',
        'max_adsorption': 'Max Adsorption',
        'pp0_range': 'P/P₀ Range',
        'yes': 'Yes',
        'no': 'No',
        'date': 'Date',
        'mode': 'Mode',
        'points': 'Points',
        'range_label': 'Range',
        'snr_label': 'SNR',
    },
    'zh': {
        'home': '首页', 'xrd': 'XRD', 'ftir': 'FTIR', 'bet': 'BET', 'projects': '项目', 'contact': '联系',
        'hero_title': '环境工程',
        'hero_subtitle': '研究与分析',
        'hero_desc': '用于生物炭、吸附剂和水处理材料的高级表征工具。上传XRD、FTIR、BET数据进行即时可视化和分析。',
        'start_analysis': '开始分析',
        'view_projects': '查看项目',
        'analysis_tools': '分析工具',
        'choose_tool': '选择您的表征方法',
        'click_tool': '点击任意工具打开其专用分析页面。',
        'xrd_desc': '峰检测、d间距、结晶度指数、晶粒尺寸',
        'ftir_desc': '官能团识别、谱带归属、基线校正',
        'bet_desc': '比表面积、孔体积、等温线分类、BJH',
        'open_xrd': '打开XRD工具',
        'open_ftir': '打开FTIR工具',
        'open_bet': '打开BET工具',
        'samples': '已分析样品',
        'research': '研究项目',
        'publications': '发表论文',
        'q1': 'Q1期刊',
        'current_projects': '当前研究项目',
        'project_desc': '专注于生物炭基材料水处理的环境工程研究。',
        'q1_target': 'Q1目标',
        'in_progress': '进行中',
        'planning': '计划中',
        'get_in_touch': '联系我们',
        'collaboration': '用于合作、数据共享或研究咨询。',
        'institution': '机构',
        'location': '地点',
        'research_focus': '研究方向',
        'biochar_water': '生物炭、水处理、重金属去除',
        'send_message': '发送消息',
        'built_for': '为研究而建。开源。',
        'drag_drop': '拖放文件',
        'browse': '浏览',
        'sample_data': '示例数据：',
        'upload_data': '上传数据或选择示例开始',
        'peak_detection': '峰检测',
        'min_peak': '最小峰高 (%)',
        'smoothing': '平滑因子',
        'peak_width': '峰宽 (点数)',
        'detect_peaks': '检测峰',
        'peak_params': '峰参数',
        'range': '范围',
        'max_intensity': '最大强度',
        'peak_count': '峰数量',
        'fwhm': '半高宽 (平均)',
        'crystallinity': '结晶度指数',
        'avg_area': '平均峰面积',
        'export_peak': '导出峰数据',
        'crystal_info': '晶体信息',
        'wavelength': '波长 (Å)',
        'instrument': '仪器',
        'calc_d': '计算d间距',
        'detailed_peak': '详细峰分析',
        'functional_group': '官能团识别',
        'spectrum_settings': '光谱设置',
        'baseline': '基线校正',
        'none': '无',
        'linear': '线性',
        'polynomial': '多项式 (2阶)',
        'rubberband': '橡皮筋',
        'savgol': '平滑 (Savitzky-Golay)',
        'normalization': '归一化',
        'max_norm': '最大归一化',
        'area_norm': '面积归一化',
        'minmax': '最小-最大',
        'spectrum_stats': '光谱统计',
        'resolution': '分辨率',
        'min_t': '最小透射率',
        'max_t': '最大透射率',
        'detected_bands': '检测谱带',
        'snr': '信噪比',
        'bet_calculator': 'BET计算器',
        'cross_section': 'N2截面积 (Å²)',
        'mol_weight': '分子量 (g/mol)',
        'stp': 'STP体积 (cm³/mol)',
        'bet_range': 'BET范围 (P/P₀)',
        'results_summary': '结果汇总',
        'surface_area': 'BET比表面积',
        'pore_volume': '总孔体积',
        'micro_volume': '微孔体积',
        'meso_volume': '介孔体积',
        'avg_pore': '平均孔径',
        'correlation': '相关系数 R²',
        'monolayer': '单层体积',
        'bet_c': 'BET常数 C',
        'isotherm_class': '等温线分类',
        'microporous': '微孔',
        'non_porous': '非孔/大孔',
        'weak': '弱相互作用',
        'mesoporous': '介孔',
        'capillary': '弱+毛细管',
        'layered': '层状',
        'detailed_data': '详细等温线数据',
        'metadata': '分析元数据',
        'export': '导出',
        'png_300': 'PNG (300 DPI)',
        'png_600': 'PNG (600 DPI)',
        'png_1000': 'PNG (1000 DPI)',
        'data_csv': '数据 (CSV)',
        'data_txt': '数据 (TXT)',
        'full_report': '完整报告',
        'no_peaks': '尚未检测峰',
        'no_dspacing': '检测峰后计算d间距',
        'upload_first': '请先上传数据',
        'detect_first': '请先检测峰',
        'xrd_analysis': 'X射线衍射数据可视化',
        'xrd_desc_long': '上传XRD数据生成出版级图表，含峰检测、d间距计算和综合元数据。',
        'ftir_analysis': '傅里叶变换红外光谱',
        'ftir_desc_long': '上传FTIR光谱进行官能团识别、峰分析和谱带归属。',
        'bet_analysis': '比表面积与孔隙分析',
        'bet_desc_long': '上传N2吸附/脱附等温线数据进行综合比表面积和孔隙表征。',
        'wavenumber': '波数 (cm⁻¹)',
        'vibration_type': '振动类型',
        'expected_range': '预期范围',
        'observed': '观测强度',
        'band_shape': '谱带形状',
        'status': '状态',
        'detected': '已检测',
        'not_detected': '未检测',
        'point_num': '点号',
        'p_p0': 'P/P₀',
        'adsorption': '吸附量 (cm³/g)',
        'desorption': '脱附量 (cm³/g)',
        'hysteresis': '滞后环',
        'bet_y': '1/[V(P₀/P-1)]',
        'in_range': '在BET范围内',
        'tea_biochar': '茶树枝生物炭',
        'koh_activated': 'KOH活化',
        'fe_modified': '铁改性生物炭',
        'zno': '氧化锌纳米颗粒',
        'tio2': '二氧化钛锐钛矿',
        'raw_biochar': '原始生物炭',
        'chitosan': '壳聚糖-生物炭',
        'meso_silica': '介孔二氧化硅',
        'macro_carbon': '大孔碳',
        'cd_removal': '茶树枝生物炭去除Cd²⁺',
        'cd_desc': '制备和表征茶树枝生物炭用于水溶液中镉的去除。',
        'pnp': 'PNP降解研究',
        'pnp_desc': '使用改性生物炭催化剂降解对硝基苯酚。动力学建模。',
        'as_removal': '铁改性生物炭去除As',
        'as_desc': '铁浸渍生物炭用于地下水砷的去除。',
        'env_eng': '环境工程系',
        'china': '中国',
        'name': '姓名',
        'email': '邮箱',
        'subject': '主题',
        'message': '消息',
        'research_collab': '研究合作',
        'data_help': '数据分析帮助',
        'general': '一般咨询',
        'platform': '环境工程研究与数据分析平台',
        'xrd_pattern': 'XRD图谱',
        'ftir_spectrum': 'FTIR光谱',
        'bet_isotherm': 'N2吸附/脱附等温线',
        'intensity_pct': '强度 (%)',
        'transmittance_pct': '透射率 (%)',
        'absorbance': '吸光度 (a.u.)',
        'n2_adsorbed': 'N2吸附量 (cm³/g STP)',
        'relative_pressure': '相对压力 (P/P₀)',
        'intensity_cps': '强度 (cps)',
        'relative_pct': '相对强度 (%)',
        'd_spacing': 'd间距 (Å)',
        'peak_area': '峰面积',
        'cryst_size': '晶粒尺寸 (nm)',
        'total_points': '总点数',
        'step_size': '步长',
        'max_int': '最大强度',
        'mean_int': '平均强度',
        'std_dev': '标准差',
        'loaded': '加载时间',
        'filename': '文件名',
        'has_desorption': '有脱附数据',
        'max_adsorption': '最大吸附量',
        'pp0_range': 'P/P₀范围',
        'yes': '是',
        'no': '否',
        'date': '日期',
        'mode': '模式',
        'points': '点数',
        'range_label': '范围',
        'snr_label': '信噪比',
    }
};

let currentLang = 'en';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('biochar-lang', lang);

    document.querySelectorAll('.lang-toggle button').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        if (LANG[lang][key]) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = LANG[lang][key];
            } else {
                el.textContent = LANG[lang][key];
            }
        }
    });

    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const key = el.dataset.i18nHtml;
        if (LANG[lang][key]) {
            const icon = el.querySelector('i');
            if (icon) {
                el.innerHTML = '';
                el.appendChild(icon);
                el.appendChild(document.createTextNode(' ' + LANG[lang][key]));
            } else {
                el.textContent = LANG[lang][key];
            }
        }
    });

    const titleEl = document.querySelector('[data-i18n-title]');
    if (titleEl && LANG[lang][titleEl.dataset.i18nTitle]) {
        document.title = LANG[lang][titleEl.dataset.i18nTitle];
    }
}

function initLanguage() {
    const saved = localStorage.getItem('biochar-lang') || 'en';
    setLanguage(saved);
}

document.addEventListener('DOMContentLoaded', initLanguage);
